name: devops app
 
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
 
      - name: List Files
        run: |
          echo "Terry is teaching"
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install flake8 pytest
 
      - name: Lint check
        run: |
          flake8 FlaskWebProject1/ runserver.py --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 FlaskWebProject1/ runserver.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
 
      - name: Run Tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t umairsaeedbhatti/devops-app:latest .

      - name: Push Docker image
        run: docker push umairsaeedbhatti/devops-app:latest

      - name: Tag and Push Docker image with version
        run: |
          docker tag umairsaeedbhatti/devops-app:latest umairsaeedbhatti/devops-app:${{ github.sha }}
          docker push umairsaeedbhatti/devops-app:${{ github.sha }}