name: Devops_Class  # Test: Added test message to trigger workflow
 
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
 #coment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
 
      - name: List Files
        run: |
          echo "Terry is teaching"
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install flake8 pytest
 
      - name: Lint check
        run: |
          flake8 FlaskWebProject1/ runserver.py --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 FlaskWebProject1/ runserver.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
 
      - name: Run Tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
 
    steps:
      - name: Check out branches
        uses: actions/checkout@v4
 
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops_class:${{github.sha}} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops_class:${{github.sha}}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_USERNAME }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: UmairFlaskApp
          publish-profile: ${{ secrets.AZURE_USERNAME }}
          images: '${{ secrets.DOCKERHUB_USERNAME }}/devops_class:${{ github.sha }}'


 