name: devops app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
   
    - name: List Files
      run: |
       echo "Umair is Learning"
    - name: Install Dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pthon -m pip install flake8
     name: devops app
 
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
 
      - name: List Files
        run: |
          echo "Terry is teaching"
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install flake8
 
      - name: Lint check
        run: |
          flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

          
        runs-on: ubuntu-latest
        needs: build
        steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production server..."
          # Add your deployment commands here, e.g., scp, rsync, etc.
          echo "Deployment complete!"
 